name: Sync
on: 
  schedule: 
    - cron: "0 * * * *"
  push:
    branches: 
      - workflows
jobs: 
  rebase:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Fetch upstream
        uses: tjusl/sync-upstream-repo@v0.1.6
        with: 
          upstream_repo: https://github.com/coreboot/coreboot.git
          upstream_branch: master
          local_branch: workflows
          github_token: ${{ secrets.GITHUB_TOKEN }}


